### PR TITLE
Update Package.swift

### PR DESCRIPTION
**Pull request by korovyev**

### CODE REVIEW

**Review by NKorchagin — APPROVED** [review]
👍

**Comment by korovyev** [comment]
@NKorchagin I think I need to tag in order for it to work with Xcode 11 - is 8.1.0 ok do you think?

**Comment by NKorchagin** [comment]
If it's breaking change for Xcode 10, then make it 9.0.0, but keep in mind that we have script for release
`BuildControl/bin/releaseMe.sh major --tag --push`

**Comment by korovyev** [comment]
Its not a breaking change, so I did a minor release - just getting it to work with Xcode 11

image

:)

**Pull request merged**
